"""reviews added

Revision ID: 9febfc6cf561
Revises: c73e77d8fcf1
Create Date: 2019-12-30 17:16:57.811436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9febfc6cf561'
down_revision = 'c73e77d8fcf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('process', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'process')
    # ### end Alembic commands ###
